name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: false
          persist-credentials: false

      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0

      - name: Format
        shell: bash
        run: |
          deno fmt
          if [ $(git status -uno --porcelain --ignore-submodules) ]
          then
            git config user.email "propelml@gmail.com"
            git config user.name "denobot"
            git add .
            git commit --message "Format code"
          fi
